name: my_instax
description: "A simple clone of instagram with touches of Twitter or 'X'"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.1.4

  user_repository:
    path: packages/user_repository
  image_picker: ^1.1.2
  image_cropper: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true